// Generated by Wrangler on Sun Apr 21 2024 22:35:52 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types ai/src/worker-configuration.d.ts`

interface Env {
	SALT_TOKEN: "sedfbveghj1t4a649t";
	DB: D1Database;
	AI: unknown;
}
